name: Update Docs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  
jobs:
  merge-to-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # all branches and tags
      - name: Upade Docs
        run: |
          bash sync.sh
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "Upadate Docs" 
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin main
